### ISSUE TITLE
关于tronWeb 生成实例问题

### ISSUE THREAD

**Issue by luozygithub** [tronprotocol/tronweb#212]
// Tronweb 最新3.2.6版本可以通过setHeader方法设置API Key参数
//示例1
const TronWeb = require('tronweb')
const HttpProvider = TronWeb.providers.HttpProvider;
const fullNode = new HttpProvider("https://api.trongrid.io");
const solidityNode = new HttpProvider("https://api.trongrid.io");
const eventServer = new HttpProvider("https://api.trongrid.io");
const privateKey = "your private key";
const tronWeb = new TronWeb(fullNode,solidityNode,eventServer,privateKey);
tronWeb.setHeader({"TRON-PRO-API-KEY": 'your api key'});

为什么要加privateKey才能生成tronWeb去通讯

**Comment by summertanh** [comment]
The reason is that if you want to connect the trongrid.io fullnode, which has requests limitation if without the key. More details please read the docs on Trongrid (https://www.trongrid.io/)

**Comment by luozygithub** [comment]
钱包与链交互时候都要加 privateKey 吗？

**Comment by summertanh** [comment]
oh, you say the privateKey, if you need to tronWeb instance manage an account information and sign transaction you need to add the privateKey when creating a tronWeb instance. Otherwise, you don't need to add it. Normally a wallet has many accounts, and privateKeys are also in the wallet. When a wallet user creates or imports an account, the tronWeb instance will setPrivateKey accordingly.
