### ISSUE TITLE
why tronweb getting privatekey in constructor? (malicious scenario)

### ISSUE THREAD

**Issue by cloud9020locki** [tronprotocol/tronweb#225]
I know that Tronweb is opensource, but this scenario can happen
Tronweb documentation suggest developer as using 
```
const tronWeb = new TronWeb(fullNode,solidityNode,eventServer,privateKey);
```
if Tronweb become malicious then all asset can be stolen! How we can trust tronweb?
No one has the right to receive the private key of the user account.
Other scenario is that Malicious library using scan of taint of Tronweb. taint vulnerability is very important here!

**Comment by summertanh** [comment]
Hi, 
If you need to send transaction or triggerconstantcontract with tronWeb, you should initiate tronWeb instance with a privateKey. At most of time, you can use a whatever privateKey such as '01' for triggerconstantcontract as the fullnode api needs the owner_address param when calling the triggerconstantcontract. 
If you are developing a wallet, the wallet should protect the uses' privaket key. tronWeb never send the privateKey, because the sign action is happened in local wallet, It is safe. Please see the link issue [https://github.com/tronprotocol/tronweb/issues/215](https://github.com/tronprotocol/tronweb/issues/215)

**Comment by cloud9020locki** [comment]
Hi,
can you get us some detail about implementation of sending transaction via the 01 private key?
you mean that we can use '01' instead of real private key, then we can use a local wallet.
could you get us some code snippet?

**Comment by summertanh** [comment]
Hi,
1. If you just query the result of a transaction, you can just set a private key such as '01'
2. but if you need to initiate a transaction that involves a signature, you need to use the correct private key

**Comment by cloud9020locki** [comment]
Hi,
at number 2, our group create nodejs api, we want to sign transaction in secure and safe way.
we must implement two important things: 
1.private key must never send to a tronweb api or third party.
2.private key on server.js must not visible, for example: using obfuscation or tabboxing method.

**Comment by summertanh** [comment]
Hi,
First of all, let's make it clear that when using the api provided by tronWeb, tronWeb will never pass the private key to any server. Your private key will always be stored locally by yourself, because only the private key will be used when signing, and signing is a local action.
Given that you are using tronWeb transactions in a node environment, you can put the private key in an online server configuration file, or the encrypted private key in the server and just keep the encrypted password strictly, only the administrator has permission to view the server private key configuration. This is just a suggestion for project security management.

**Comment by cloud9020locki** [comment]
Hi
We are fully aware of what you have written, but the question is how to trust Tronweb and enter a private key into it.
Thank you for your generosity in response.

**Comment by rof20004** [comment]
Sorry for wake up this issue, but how can I do this?


If you just query the result of a transaction, you can just set a private key such as '01' ???
