### ISSUE TITLE
`triggerConstantContract` and `estimateenergy` do not return the correct energy amounts

### ISSUE THREAD

**Issue by mattiaferrari02** [tronprotocol/tronweb#487]
I'm using this snippet of code to get the current energy consumed by a TRC20 transfer
```
const res = await tron.current.transactionBuilder.estimateEnergy(
      "TR7NHqjeKQxGTCi8q8ZY4pL8otSzgjLj6t",
      "transfer(address,uint256)",
      { feeLimit: 10000000, callValue: 0 },
      [
        { type: "address", value: address,
        { type: "uint256", value: tokenAmount }
      ]
    )
```
I'm getting always a value like `33889` but when I broadcast the transaction I see in tronscan that the energy consumed sometimes doubles and if I use a fee limit too low the transaction goes out-of-gas
For example [this](https://tronscan.org/#/transaction/f102b9f80d1c83fea7f24a0173fa3ab1e41a710431271847705677abae359456)
The transaction burned 27 TRX for energy but when I try calling `triggerConstantContract` I get the wrong values:
```
energy_used: 31895, energy_penalty 17245 (= 14 TRX)
```
how can I get the correct energy values?

**Comment by start940315** [comment]
<img width="754" alt="Screenshot 2024-02-28 at 2 18 52 PM" src="https://github.com/tronprotocol/tronweb/assets/4272575/94ecbe32-45ff-4282-b21f-34b29edc02ae">

Because you triggered a frequently used contract and caused 35,245 extra Energy consumption.

**Comment by ferdinand026** [comment]
@mattiaferrari02 That is because a transfer to an address with a USDT balance of 0 will require 15,000 more energy than a transfer to an address with some USDT.

You passed an account addrsss whoes USDT balance is not zero when invoking the triggerConstantContract API, then the returned energy_used will be 30k+, but when you transafer USDT acturally, you pass an account address whoes USDT balance is zero, at this situation, the energy_used will be 60k+. 

If you passed an account addrsss whoes USDT balance is zero when invoking the triggerConstantContract API, then the returned energy_used will be 60k+.

**Comment by ferdinand026** [comment]
@mattiaferrari02 When the `SSTORE` storage instruction in TVM assigns a value to a variable, if the variable value is empty, it will consume 20,000 energy, otherwise, it will only consume 5,000 energy. Therefore, for a certain TRC20 Token transfer, if the balance of the TRC20 token of the receiving account is 0, the energy consumed by the transfer will consume 15,000 more energy than when the balance is not 0. Please refer to this document: https://developers.tron.network/docs/faq#16-why-do-two-transfer-transactions-of-the-same-trc20-token-consume-different-energy .

**Comment by PVZMF** [comment]
@mattiaferrari02 
I also faced the problem, could you solve the problem?
When I enter different amounts of tokens, the energy does not change
