### ISSUE TITLE
A typo in `latest_operation_time`?

### ISSUE THREAD

**Issue by basharov** [tronprotocol/tronweb#495]
When I call `tronWeb.trx.getAccount(address)`, I see an object where there is a key `latest_opration_time`, which probably is with a typo and should be `latest_operation_time` instead?

**Comment by ferdinand026** [comment]
@basharov It is not an issue of tronweb, the return value of "tronWeb.trx.getAccount(address)" is acturally returned by java-tron node. This is a legacy issue with TRON protobuf, there is a typo in [TRON protobuf](https://github.com/tronprotocol/protocol/blob/2a678934da3992b1a67f975769bbb2d31989451f/core/Tron.proto#L169C70-L169C89), and it is marked as "FIXME fix grammar" to plan to fix it in the furture releases. But since protobuf changes may affect surrounding projects, more discussion is needed. And once the java-tron code is fixed, the typo in returned value of getAccount API of tronweb will be fixed automatically.
